---
- name: "Do systemd daemon reload"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "protocol-solana : Do systemd daemon reload"

- name: "Restart Solana service"
  become: true
  ansible.builtin.systemd:
    name: "solana"
    state: "restarted"
    no_block: true
  listen: "protocol-solana : Restart solana service"
