---
- name: "Set service username fact"
  ansible.builtin.set_fact:
    service_username: "svc"

- name: "Make your computer speak"
  delegate_to: "localhost"
  ansible.builtin.shell:
    cmd: >-
      osascript -e 'say "Hello from Kerosene" speaking rate 140 pitch 42 modulation 60' || :
