---
name: "Check formatting and linting"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: "always"

jobs:
  format-and-lint:
    name: "Check formatting and linting"
    runs-on: ["ubuntu-latest"]
    permissions:
      checks: "write"
    steps:
      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@v4"
        with:
          filter: "tree:0"

      - id: "setup-toolchain"
        name: "Install Rust toolchain"
        uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "stable"

      - id: "setup-cache"
        name: "Cache dependencies"
        uses: "Swatinem/rust-cache@v2"

      - id: "fmt"
        name: "Check formatting"
        run: |
          cargo fmt --all -- --check

      - id: "clippy"
        name: "Run Clippy"
        uses: "auguwu/clippy-action@1.4.0"
        with:
          token: "${{ github.token }}"
